2023-05-03 14:58:13,395 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-05-03 14:58:13,395 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Configure stats pid to 11044
2023-05-03 14:58:13,395 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Anton\.config\wandb\settings
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Loading settings from f:\Glaucoma\wandb\settings
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_init.py:_log_setup():507] Logging user logs to f:\Glaucoma\wandb\run-20230503_145813-0x001\logs\debug.log
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_init.py:_log_setup():508] Logging internal logs to f:\Glaucoma\wandb\run-20230503_145813-0x001\logs\debug-internal.log
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002313C1EB880>
2023-05-03 14:58:13,396 INFO    MainThread:11044 [wandb_init.py:init():547] calling init triggers
2023-05-03 14:58:13,398 INFO    MainThread:11044 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'Dataset': 'Glaucoma', 'Models': 'Xception', 'learning_rate': 0.001, 'momentum': 0.9, 'metrics': ['accuracy']}
2023-05-03 14:58:13,398 INFO    MainThread:11044 [wandb_init.py:init():596] starting backend
2023-05-03 14:58:13,398 INFO    MainThread:11044 [wandb_init.py:init():600] setting up manager
2023-05-03 14:58:13,402 INFO    MainThread:11044 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-03 14:58:13,406 INFO    MainThread:11044 [wandb_init.py:init():606] backend started and connected
2023-05-03 14:58:13,422 INFO    MainThread:11044 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-03 14:58:13,425 INFO    MainThread:11044 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-03 14:58:13,425 INFO    MainThread:11044 [wandb_init.py:init():700] updated telemetry
2023-05-03 14:58:13,442 INFO    MainThread:11044 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-03 14:58:13,843 ERROR   MainThread:11044 [wandb_init.py:init():763] encountered error: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (0x001) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2023-05-03 14:58:14,085 ERROR   MainThread:11044 [wandb_init.py:init():1168] You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (0x001) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
Traceback (most recent call last):
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
  File "c:\Users\Anton\anaconda3\envs\ML\lib\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.UsageError: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (0x001) that does not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
2023-05-03 14:58:31,343 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Current SDK version is 0.15.1
2023-05-03 14:58:31,343 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Configure stats pid to 11044
2023-05-03 14:58:31,344 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Anton\.config\wandb\settings
2023-05-03 14:58:31,344 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Loading settings from f:\Glaucoma\wandb\settings
2023-05-03 14:58:31,344 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-03 14:58:31,344 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-03 14:58:31,344 INFO    MainThread:11044 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-05-03 14:58:31,345 INFO    MainThread:11044 [wandb_init.py:_log_setup():507] Logging user logs to f:\Glaucoma\wandb\run-20230503_145831-0x001\logs\debug.log
2023-05-03 14:58:31,345 INFO    MainThread:11044 [wandb_init.py:_log_setup():508] Logging internal logs to f:\Glaucoma\wandb\run-20230503_145831-0x001\logs\debug-internal.log
2023-05-03 14:58:31,345 INFO    MainThread:11044 [wandb_init.py:init():547] calling init triggers
2023-05-03 14:58:31,345 INFO    MainThread:11044 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'Dataset': 'Glaucoma', 'Models': 'Xception', 'learning_rate': 0.001, 'momentum': 0.9, 'metrics': ['accuracy']}
2023-05-03 14:58:31,346 INFO    MainThread:11044 [wandb_init.py:init():596] starting backend
2023-05-03 14:58:31,346 INFO    MainThread:11044 [wandb_init.py:init():600] setting up manager
2023-05-03 14:58:31,350 INFO    MainThread:11044 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-05-03 14:58:31,353 INFO    MainThread:11044 [wandb_init.py:init():606] backend started and connected
2023-05-03 14:58:31,373 INFO    MainThread:11044 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-05-03 14:58:31,374 INFO    MainThread:11044 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-05-03 14:58:31,374 INFO    MainThread:11044 [wandb_init.py:init():700] updated telemetry
2023-05-03 14:58:31,377 INFO    MainThread:11044 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-03 14:58:32,454 INFO    MainThread:11044 [wandb_run.py:_on_init():2177] communicating current version
2023-05-03 14:58:32,844 WARNING MsgRouterThr:11044 [router.py:message_loop():77] message_loop has been closed
2023-05-03 14:58:32,844 INFO    MainThread:11044 [wandb_run.py:_on_init():2186] got version response 
2023-05-03 14:58:32,845 INFO    MainThread:11044 [wandb_init.py:init():787] starting run threads in backend
2023-05-03 14:58:49,650 INFO    MainThread:11044 [wandb_run.py:_console_start():2158] atexit reg
2023-05-03 14:58:49,651 INFO    MainThread:11044 [wandb_run.py:_redirect():2013] redirect: SettingsConsole.WRAP_RAW
2023-05-03 14:58:49,651 INFO    MainThread:11044 [wandb_run.py:_redirect():2078] Wrapping output streams.
2023-05-03 14:58:49,651 INFO    MainThread:11044 [wandb_run.py:_redirect():2103] Redirects installed.
2023-05-03 14:58:49,652 INFO    MainThread:11044 [wandb_init.py:init():829] run started, returning control to user process
